# Proxy services configuration for LOCAL environment
proxy:
  services:
    - name: my-service
      domain: my-service.my-company.com
      strategy: round-robin
      hosts:
        - address: "127.0.0.1"
          port: 9090
        - address: "127.0.0.1"
          port: 9091
