# Proxy services configuration for PRODUCTION environment
proxy:
  listen:
    address: "127.0.0.1"
    port: 8080
  services:
    - name: my-service
      domain: my-service.my-company.com
      strategy: round-robin
      hosts:
        - address: "10.0.0.1"
          port: 9090
        - address: "10.0.0.2"
          port: 9090
