spring:
  application:
    name: reverse-proxy
  profiles:
    active: local  # Default profile (change to 'prod' for production)

# Logging configuration
logging:
  level:
    com.marco.reverseproxy: INFO
    com.marco.reverseproxy.cache: DEBUG  # Enable cache logging
    reactor.netty: WARN
    io.netty: WARN

# Server configuration
server:
  address: ${proxy.listen.address}
  port: ${proxy.listen.port}
  netty:
    connection-timeout: 5s
    idle-timeout: 30s
